apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster1-webserver
  namespace: cluster1-webserver
  labels:
    app: cluster1-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster1-webserver
  template:
    metadata:
      labels:
        app: cluster1-webserver
      annotations:
        proxy.istio.io/config: |
          proxyMetadata:
              ISTIO_META_DNS_CAPTURE: "true"
              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    spec:
      serviceAccountName: cluster1-webserver-service-account
      containers:
        - name: cluster1-webserver
          image: public.ecr.aws/nginx/nginx:stable-perl
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
