apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster1-webserver-service-account
  namespace: cluster1-webserver
  #annotations: only add if we need get resources from AWS
  #eks.amazonaws.com/role-arn: arn:aws:iam::171057908863:role/cluster2DevStack-aresRole0B8A3CEF-wlHxUhLLn4Fo
